### PR TITLE
27 fix i18n problem

### LINKED ISSUE #27: I18n problems
Hi XDEV,
I have tested today your component. First of all, it's great!

But while developing I discovered some problems with translating the component:

1. If I apply another dateRangeLocalizerFunction, it is never called. The set of the LabelGenerator is called in `initUI` of DateRangePickerOverlay, which is called on constructor invocation. So the change afterward doesn't have any effect.
https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePickerOverlay.java#L95

It should be applied like the translation for the DatePickers in the `AttachEvent`.
I could create a pull request for this.

2. I think there could be a more uniform way to access the labels of the DatePickers and the Combobox. This is only a suggestion. I discovered these while using this component. Some documentation/tutorial could also help here.

I am also from Germany, so we could communicate in german. Feel free to contact me.

Best regards,
Dario

### PR DESCRIPTION
**Pull request by AB-xdev**
Fix #27

### CODE REVIEW

File: vaadin-date-range-picker-demo/src/main/java/software/xdev/vaadin/daterange_picker/example/customized/CustomDateRange.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+public class CustomDateRange extends AbstractDateRange<CustomDateRange>
+{
+	/**
+	 * Stores some data
+	 */
+	private String tag;
+	
+	public CustomDateRange withTag(final String tag)
+	{
+		this.tag = tag;
```
Comment (tboehm-xdev) [inline vaadin-date-range-picker-demo/src/main/java/software/xdev/vaadin/daterange_picker/example/customized/CustomDateRange.java:14]:
```suggestion
		this.tag = tag != null ? tag : "";
```

File: vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java [hunk 2]
```diff
@@ -352,6 +389,35 @@ public Div getOverlayContainer()
...
+	
+	/**
+	 * Sets the label for the overlay DateRange-ComboBox
+	 * @param label
+	 */
+	public void setDateRangeOptionsLabel(final String label)
+	{
+		this.getOverlay().getCbDateRange().setLabel(label);
+	}
+
```
Comment (tboehm-xdev) [inline vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java:420]: It would be great to have some _null_ checks here, what do you mean @AB-xdev

**Review by tboehm-xdev — CHANGES_REQUESTED** [review]
@AB-xdev please check my comments about null checks

File: vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java (hunk 2 above)
Comment (AB-xdev) [reply vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java:420]: @tboehm-xdev 
Sounds like a good idea 👍

**Review by tboehm-xdev — APPROVED** [review]
Looks good.
